name: Workflow 2 in Repo2

on:
  workflow_call:
    inputs:
      input1:
        description: First input variable
        required: false
        type: string
      input2:
        description: Second input variable
        required: false
        type: string
    secrets:
      secret_key:
        description: A secret for authentication

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Display Inputs
        run: |
          echo "Input 1: ${{ inputs.input1 }}"
          echo "Input 2: ${{ inputs.input2 }}"
      
      - name: Use Secret
        run: echo "Using secret ${{ secrets.secret_key }}"

  checkout-and-print:
    runs-on: ubuntu-latest
    needs: process  # Ensures this job runs after `process`
    steps:
      - name: Checkout Repo2
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Fetch only the latest commit

      - name: Print Repository and Branch
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
